version: '3.8'

services:
  app:
    build:
      context: ./server
    ports:
      - "3000:3000"
    container_name: myapp-backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - app
    container_name: myapp-nginx
